spring:
  application:
    name: remember_words
  datasource:
    url: jdbc:mysql://localhost:3309/remember_words?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: remember_words
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 60000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 180000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 8090

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xl.remember.words.entity


translate:
  baidu:
    appId: 20240809002119631
    secret: qNBmdRfBe6ufJO2sowwX
    url: https://fanyi-api.baidu.com/api/trans/vip/translate
